#!/bin/bash

usage() {
    echo "Usage: $0 <file> [lang]"
    echo "Examples:"
    echo "$ $0 movie.avi pob         # brazilian portuguese"
    echo "$ $0 movie.avi por,pob     # any portuguese"
    echo "$ $0 movie.avi eng         # english"
    echo "$ $0 movie.avi all         # any language"
    exit
}

if [ $# -lt 1 ]; then
    usage
elif [ $# -gt 2 ]; then
    usage
fi

if [ $# = 2 ]; then
    lang=$2
else
    lang="all"
fi

echo "Requested language: $lang"
output=$(echo "$1" | sed 's/\.[^.]*$/.srt/')
oshash=$(oshash "$1")
if [ "$?" = 1 ]; then
    echo "Error: oshash returned 1"
    exit
fi
echo "Movie hash: $oshash"

subid=$(wget "http://www.opensubtitles.org/en/search/sublanguageid-$lang/moviehash-$oshash/rss_2_00" -q -O - \
    | grep '.*en/subtitles' | sed 's|.*en/subtitles/||; s|/.*||' | head -n1)
if [ -z "$subid" ]; then
    echo "Error: subtitle not found"
    exit
fi
echo "Subtitle ID: $subid"

tmp_zip=/tmp/$subid.zip
tmp_dir=/tmp/$subid
download_url=http://dl.opensubtitles.org/en/download/sub/$subid

echo "Downloading: $download_url"
wget $download_url -q -O $tmp_zip
unzip -d $tmp_dir $tmp_zip > /dev/null && rm $tmp_zip

if [ -f $tmp_dir/$output ]; then
  subtitle=$tmp_dir/$output
else
  echo "  > Multiple subtitles found: $(ls -1 $tmp_dir/*.srt)"
  subtitle=$(ls -1 $tmp_dir/*.srt | head -n1)
  echo "  > Choosing: $subtitle"
fi
cp $subtitle $output
rm -rf $tmp_dir

echo "Subtitle: $output"
echo "Enjoy! [DONE]"
